dbtdatabricks:
  outputs:
    dev:
      catalog: dbt
      host: 2564969634619905.5.gcp.databricks.com
      http_path: /sql/1.0/warehouses/9f7f07f31f8a5ea8
      schema: raw
      threads: 1
      token: dapid72e53151b2459cad6d2356dc13943a3
      type: databricks
  target: dev
dbtlearns:
  outputs:
    dev:
      dbname: Banking
      host: localhost
      pass: Quizquiz26
      port: 5432
      schema: test
      threads: 1
      type: postgres
      user: postgres
  target: dev
dbtlearn:
  outputs:
    dev:
      account: RSAMRPC-IU16610
      database: AIRBNB
      password: dbtPassword123
      role: transform
      schema: DEV
      threads: 1
      type: snowflake
      user: dbt
      warehouse: COMPUTE_WH
  target: dev
postgres:
  outputs:
    dev:
      dbname: Banking
      host: localhost
      pass: Quizquiz26
      port: 5432
      schema: test
      threads: 1
      type: postgres
      user: postgres
  target: dev
